-- https://github.com/premake/premake-core/issues/1306#issuecomment-629194693
-- Thanks :)

require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
    premake.w('<VcpkgEnableManifest>true</VcpkgEnableManifest>')
    premake.w('<VcpkgUseStatic>true</VcpkgUseStatic>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)
