// RPFXplorer.idl : IDL source for RPFXplorer
//

// This file will be processed by the MIDL tool to
// produce the type library (RPFXplorer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4cceecac-fbdc-4487-a6cf-c21f49f8f477),
	pointer_default(unique)
]
interface IShellFolderImpl : IUnknown
{
};

[
	object,
	uuid(0EA6B88C-6FC4-4DBC-AE9C-7D3BFE2C9FF9),

	helpstring("IShellViewImpl Interface"),
	pointer_default(unique)
]
interface IShellViewImpl : IUnknown
{
};


////////////////

[
	uuid(0dfd9ea1-e255-4fb0-b40b-98a0a77dc9c8),
	version(1.0),
]
library RPFXplorerLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[uuid(397481b8-1b95-41dc-bfe1-0c3f98e504ee)]
	coclass ShellFolderImpl
	{
		[default] interface IShellFolderImpl;
	};

	[uuid(E6B437AF-F4E6-4731-B04A-D520FD1F4ED6)]
	coclass ShellViewImpl
	{
		[default] interface IShellViewImpl;
	};
};
